name: Build LaTeX document
on:
  release:
    types: [created]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: thesis/
          root_file: main.tex
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: thesis/main.pdf
